---
title: "Juul_work_scrap"
author: "Ali"
date: "30/07/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(dev.args = list(png = list(type = "cairo")))
```

```{r frechet_dist, eval=FALSE}
m <- m[,1:10] ## a pilot test for the first 10 trajs
n_traj <- ncol(m)
dmat_fr <- matrix(NA, n_traj, n_traj) ## Frechet
diag(dmat_fr) <- 0
## drop 1 column of matrix of trajectories in order, make a submatrix, save it in a traj_list element
traj_list <- sapply(1:(n_traj-1), FUN=function(i) subset.matrix(m,select = c(i:n_traj)))
## go through the traj_list, compute the distance of each traj wrt all trajs after it  
system.time(out_traj_list <- sapply(traj_list,dtraj))

dmat_fr <- matrix(NA, n_traj, n_traj) ## distance matrix for Frechet dist
diag(dmat_fr) <- 0
## put the list on the dist matrix rows
 for(i in 1:(n_traj-1)) {
   dmat_fr[i,(i+1):n_traj] <- out_traj_list[[i]]
 }

dmat_fr <- make_symm(dmat_fr)
stopifnot(isSymmetric(dmat_fr))
# write.table(dmat_fr,"./data/dmat_juul_frechet.csv",sep=",",row.names = FALSE, col.names = FALSE)

## Do the same for DTW
# dmat_DTW <- make_symm(dmat_DTW)
# stopifnot(isSymmetric(dmat_DTW))
# write.table(dmat_DTW,"./data/dmat_DTW.csv",sep=",",row.names = F,
#                  col.names = F)

```



