---
title: "Juul's paper"
author: "Ali"
date: "`r format(Sys.time(),'%d %b %Y')`"
output: html_document
bibliography: ../AliMac.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(dev.args = list(png = list(type = "cairo")))
```

```{r packages, echo=FALSE, message=FALSE}
##setwd("~/projects/AliMac_scripts/scripts/")
library(reticulate) ## 
##use_python("/usr/bin/python3")
library(SimilarityMeasures) ## for Fréchet distance computation
library(tidyverse)
source('functions.R')
```


## Juul et al's sample data set

This is inspired by @juul2021fixed. 
Retrieving and unpacking the simulated epidemic curves from
the [curvestat repo](https://github.com/jonassjuul/curvestat/).

`npy`-loading instructions  taken from [here](https://cran.r-project.org/web/packages/RcppCNPy/vignettes/UsingReticulate.pdf)

```{r get_juul}
if (!file.exists("./data/juul1.csv")) {
    download.file("https://github.com/jonassjuul/curvestat/raw/master/curvestat/tests/test_data/curves_DKE3.npy", dest="./data/juul1.npy")
    library(reticulate)
    np <- import("numpy")
    a <- np$load("./data/juul1.npy",allow_pickle=TRUE)[[1]]
    m <- do.call(cbind,a)
    write.table(m,file="./data/juul1.csv",row.names=FALSE,col.names=FALSE,
                sep=",")
} else {
    m <- as.matrix(read.csv("./data/juul1.csv")) ## the columns are the trajs
}
```

```{r plot_juul}
par(las=1,bty="l")
matplot(m,type="l",col=adjustcolor("black",alpha.f=0.2), lty=1,
        ylab="")
```



```{r frechet_dist, eval=FALSE}
m <- m[,1:10] ## a pilot test for the first 10 trajs
n_traj <- ncol(m)
dmat_fr <- matrix(NA, n_traj, n_traj) ## Frechet
diag(dmat_fr) <- 0
## drop 1 column of matrix of trajectories in order, make a submatrix, save it in a traj_list element
traj_list <- sapply(1:(n_traj-1), FUN=function(i) subset.matrix(m,select = c(i:n_traj)))
## go through the traj_list, compute the distance of each traj wrt all trajs after it  
system.time(out_traj_list <- sapply(traj_list,dtraj))

dmat_fr <- matrix(NA, n_traj, n_traj) ## distance matrix for Frechet dist
diag(dmat_fr) <- 0
## put the list on the dist matrix rows
 for(i in 1:(n_traj-1)) {
   dmat_fr[i,(i+1):n_traj] <- out_traj_list[[i]]
 }

dmat_fr <- make_symm(dmat_fr)
stopifnot(isSymmetric(dmat_fr))
write.table(dmat_fr,"./data/dmat_juul_frechet.csv",sep=",",row.names = FALSE, col.names = FALSE)

## Do the same for DTW
# dmat_DTW <- make_symm(dmat_DTW)
# stopifnot(isSymmetric(dmat_DTW))
# write.table(dmat_DTW,"./data/dmat_DTW.csv",sep=",",row.names = F,
#                  col.names = F)

```



```{r install_curvestat, echo=FALSE}
## ~/Downloads$ sudo apt-get install python3-pip
## clone the curvestats in projects dir
## pip3 install curvestat
py_install("curvestat",pip=TRUE)
while (!py_module_available("curvestat")) {
    py_install("../curvestat",pip=TRUE)
}

## create a new environment 
## conda_create("r-reticulate")
## install curvestat
## conda_install("r-reticulate", "curvestat")
## curvestat <- import("curvestat")

# py_install("panda",pip=TRUE)
```

```{r}
download.file("https://github.com/jonassjuul/curvestat/raw/master/curvestat/tests/test_data/curves_DKE3.npy", dest="./data/juul1.npy")
```

```{python}
## Note I couldn't run this in python chunk here, I ran in in systhem python3 
from curvestat import CurveBoxPlot
from curvestat import LoadRisk
## import os
## os.getcwd()
import numpy as np
import pandas as pd
dic_solutions_future = pd.read_csv("./data/juul1.csv")
## dic_solutions_future = np.load("./data/juul1.npy", allow_pickle = True)
## type(dic_solutions_future)
## 149 rows (time points) x 500 curves
nt = dic_solutions_future.shape[0]
time_arr = np.arange(0,nt)
J_vals = [2, 5, 10, 20, 30, 40, 50]
results = np.zeros(shape = (nt, 4*len(J_vals)))
for Ji in range(len(J_vals)):
    print(Ji)
    Boxplot = CurveBoxPlot(curves=dic_solutions_future,sample_curves=J_vals[Ji],
                           sample_repititions=500,time=time_arr)
    rank_allornothing=Boxplot.rank_allornothing()
    # Get envelope with this choice of ranking
    boundaries = Boxplot.get_boundaries(rank_allornothing,percentiles=[50,90])
    b_lwr50 = boundaries['curve-based'][50]['min-boundary']
    b_upr50 = boundaries['curve-based'][50]['max-boundary']
    b_lwr90 = boundaries['curve-based'][90]['min-boundary']
    b_upr90 = boundaries['curve-based'][90]['max-boundary']
    results[:, 2*Ji] = b_lwr50
    results[:, 2*Ji + 1] = b_upr50
    results[:, 2*Ji + 2] = b_lwr90
    results[:, 2*Ji + 3] = b_upr90
np.savetxt("./data/juul_boundary1.csv", results, delimiter=',')
## plotting ...
## import matplotlib.pyplot as plt
## plt.plot()
## plt.show()
```


```{r plotting}
bnds_juul <- read_csv("./data/juul_boundary1.csv", col_names = FALSE) ## the columns are 
```


# References



